version: 2.1

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cimg/elixir:1.14.0-erlang-25.0.4-node
      environment:
        MIX_ENV: test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cgc-deps-cache-{{ checksum "mix.lock" }}
            - cgc-deps-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - save_cache:
          key: cgc-deps-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .mix

  credo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run credo
          command: mix credo

  check_formatted:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Verify formatted
          command: mix format --check-formatted

  # This project isn't ready for this yet.
  # dialyzer:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - restore_cache:
  #         keys:
  #           - cgc-plt-cache-{{ checksum "mix.lock" }}
  #           - cgc-plt-cache
  #     - run: mix dialyzer --plt
  #     - save_cache:
  #         key: cgc-plt-cache-{{ checksum "mix.lock" }}
  #         paths:
  #           - _build
  #           - ~/.mix
  #     - run:
  #         name: Run dialyzer
  #         command: mix dialyzer

  test_and_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install node
          command: |
            curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
            sudo apt-get install -y nodejs
            node -v
      - run:
          name: Install npm
          command: |
            curl -L https://npmjs.org/install.sh | sudo sh
            npm -v
            npm update
            npm install --no-package-lock
      - run:
          name: Test & Analyze coverage
          command: mix coveralls

workflows:
  version: 2
  continuous_integration:
    jobs:
      - build
      - credo:
          requires:
            - build
      # - dialyzer:
      #     requires:
      #       - build
      - test_and_coverage:
          requires:
            - build
      - check_formatted:
          requires:
            - build
